const testimonialData = [ { id : 1, image : `image/Bitmap.png`, First_Name : `Anallese`, department : `Marketing`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.` , active:`active` },
                   { id : 2, image : `image/Bitmap.png`, First_Name : `Theodosia`, department : `Product Management`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.` ,active:``},
                   { id : 3, image : `image/Bitmap.png`, First_Name : `Wain`, department : `Accounting`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. `,active:`` },
                   { id : 4, image : `image/Bitmap.png`, First_Name : `Olympe`, department : `Services`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. `,active:`` },
                   { id : 5, image : `image/Bitmap.png`, First_Name : `Kaleena`, department : `Marketing`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.`,active:`` },
                   { id : 6, image : `image/Bitmap.png`, First_Name : `Fletcher`, department : `Training`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. `,active:`` },
                   { id : 7, image : `image/Bitmap.png`, First_Name : `Ruthann`, department : `Sales`, text : `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. ` ,active:``},
              ]

 newData = () =>testimonialData;